BlogApp/Controllers/BlogController.cs
using BlogApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.Controllers
{
    public class BlogController : Controller
    {

        //It return the Page where you wrote your Post
        [HttpGet]
        public ViewResult Post()
        {
            BlogRepos.Clean();
            BlogRepos.GetPosts();
            
            return View("Post");
        }



        //It validated your post and store it into database 
        [HttpPost]
        public ViewResult Post(Blog b)
        {
           // String refrence=HttpContext.Session.GetString("refrence");
            //int refr = Int32.Parse(refrence);

            if (ModelState.IsValid)
            {
                try
                {
                    string connectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Blog;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
                    SqlConnection con = new SqlConnection(connectionString);
                    con.Open();
                    string query = $"insert into post(Title, Context)values('{b.Title}', '{b.Context}')";
                    SqlCommand cmd = new SqlCommand(query, con);
                    int insertedRow = cmd.ExecuteNonQuery();
                    if (insertedRow >= 1)
                    {

                        // Clean the previous List and Get Latest Data From DB into it
                        BlogRepos.Clean();
                        BlogRepos.GetPosts();
                        //Return Front Page 
                        return View("Front", BlogRepos.blog);

                    }
                    else
                    {
                        return View("Error");
                    }
                    // users.Add(u);

                }
                catch (Exception ex)
                {
                    return View("Error");
                }
            }
            else
            {
                return View();
            }

        }


        // Show the post Details By finding its ID it the Blog Type List 
        public ViewResult Detail(int id)
        {

            // Clean the previous List and Get Latest Data From DB into it
            BlogRepos.Clean();
            BlogRepos.GetPosts();
            Blog b = BlogRepos.blog.Find(b => b.Id == id);

            return View("Detail", b);
        }


           // Return the Update Page where attributes are filled according to its ID
        [HttpGet]
        public ViewResult Update(int id)
        {

            // Clean the previous List and Get Latest Data From DB into it
            BlogRepos.Clean();
            BlogRepos.GetPosts();
            Blog b = BlogRepos.blog.Find(b => b.Id == id);

            return View("Update", b);
        }


            // Get Updated Post Data from Page and Stores it into DB
        [HttpPost]
        public ViewResult Update(Blog bl)
        {
            // Clean the previous List and Get Latest Data From DB into it
            BlogRepos.Clean();
            BlogRepos.GetPosts();
            if (ModelState.IsValid)
            {
                foreach (Blog b in BlogRepos.blog)
                {
                    if (b.Id == bl.Id)
                    {
                        b.Title = bl.Title;
                        b.Context = bl.Context;
                        try
                        {
                            string connectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Blog;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
                            SqlConnection con = new SqlConnection(connectionString);
                            con.Open();
                            string query = $"Update post set Title='{b.Title}', Context='{b.Context}' where id={b.Id} ";
                            SqlCommand cmd = new SqlCommand(query, con);
                            int effectedRow = cmd.ExecuteNonQuery();
                            if (effectedRow >= 1)
                            {
                                // Clean the previous List and Get Latest Data From DB into it
                                BlogRepos.Clean();
                                BlogRepos.GetPosts();
                                return View("Front", BlogRepos.blog);

                            }
                            else
                            {
                                return View();
                            }
                            // users.Add(u);

                        }
                        catch (Exception ex)
                        {
                            ViewBag.Error = ex.Message;
                            return View("Error");
                        }

                    }
                }

            }
            
            return View();
        }

            // Delete the Post from DB By finding it through its ID in List
        public ViewResult Remove(int id)
        {

            // Clean the previous List and Get Latest Data From DB into it
            BlogRepos.Clean();
            BlogRepos.GetPosts();
            Blog b = BlogRepos.blog.Find(b => b.Id == id);

            try
            {
                string connectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Blog;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
                SqlConnection con = new SqlConnection(connectionString);
                con.Open();
                string query = $"delete from post where id={b.Id} ";
                SqlCommand cmd = new SqlCommand(query, con);
                int effectedRow = cmd.ExecuteNonQuery();
                if (effectedRow >= 1)
                {
                    // Clean the previous List and Get Latest Data From DB into it
                    BlogRepos.Clean();
                    BlogRepos.GetPosts();
                    return View("Front", BlogRepos.blog);

                }
                else
                {
                    return View();
                }
                // users.Add(u);

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("Error");
            }

            
        } 


    }


}
         
    

BlogApp/Controllers/UserController.cs
using BlogApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.Controllers
{
    public class UserController : Controller
    {

        // Return The  Dummy About Page
        public ViewResult About()
        {
            return View("About");
        }

       
        // Return the Very First Page
        [HttpGet]
        public ViewResult Login()
        {
            return View("Index");
        }


        // Gets Data From Login Form Validets it From DB and return accordingly
        [HttpPost]
        public ViewResult Login(Users u)
        {
            

            try
            {
                string connectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Users;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
                SqlConnection con = new SqlConnection(connectionString);
                con.Open();
                string query = $"select * from users where Email='{u.RegisterEmail}' and Password='{u.RegisterPassword}'";
                SqlCommand cmd = new SqlCommand(query, con);
                SqlDataReader dr = cmd.ExecuteReader();

               // int r= (int)dr.GetValue(0);
                //String r1 = r.ToString();
                //HttpContext.Session.SetString("refrence",r1);

                if (dr.Read())
                {


                    // Admin Values are HardCodded it should be following
                    if (u.RegisterEmail == "admin@admin.com" && u.RegisterPassword == "admin")
                    {
                        //Get All users from Db
                        UsersRepos.Users();
                        
                        return View("Admin",UsersRepos.users);
                        
                    }
                    else
                    {
                        // Clean the previous List and Get Latest Data From DB into it
                        BlogRepos.Clean();
                        BlogRepos.GetPosts();
                        return View("Front",BlogRepos.blog);
                        //, BlogRepos.blog);
                    }
                }
                else
                {
                    return View("Index");
                }
                // users.Add(u);

            }
            catch (Exception ex)
            {
                ViewBag.Exception = ex.Message;
                return View("Error");
            }


        }


        // Return the Register Page
        [HttpGet]
        public ViewResult Register()
        {
            return View("Register");
        }

        // Get Data from Register Page And Stores it into DB
        [HttpPost]
        public ViewResult Register(Users u)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    string connectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Users;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
                    SqlConnection con = new SqlConnection(connectionString);
                    con.Open();
                    string query = $"insert into users (Uname,Email,Password,Image)values('{u.RegisterUsername}','{u.RegisterEmail}','{u.RegisterPassword}','{u.ProfileImage}' )";
                    SqlCommand cmd = new SqlCommand(query, con);
                    int insertedRow = cmd.ExecuteNonQuery();
                    if (insertedRow >= 1)
                    {
                        return View("Index");
                    }
                    else
                    {
                        return View();
                    }
                    // users.Add(u);

                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.Message;
                    return View("Error");
                }
            }
            else
            {

                return View();
            }

        }

        //Return The Front Page When user clicks on "Home" in NavBar
        public ViewResult Front()
        {
            // Clean the previous List and Get Latest Data From DB into it
            BlogRepos.Clean();
            BlogRepos.GetPosts();

            return View("Front", BlogRepos.blog);
        }

        //Find The Current Logged In user in List By using its ID and return Profile Page
        public ViewResult Profile(int id)
        {
            UsersRepos.users.Clear();
            UsersRepos.Users();
            Users u = UsersRepos.users.Find(u => u.Id == id);

            
            return View("Profile",u);
        }





        //       All The Below Functions Are Related To Admin Panel 




        // To update any User 
        [HttpGet]
        public ViewResult Update(int id)
        {


            UsersRepos.users.Clear();
            UsersRepos.Users();
            Users u = UsersRepos.users.Find(b => b.Id == id);

            return View("UpdateUser", u);
        }

        // Store The Updated User Attributes into DB
        [HttpPost]
        public ViewResult Update(Users bl)
        {
            UsersRepos.users.Clear();
            UsersRepos.Users();
            if (ModelState.IsValid)
            {
                foreach (Users u in UsersRepos.users)
                {
                    if (u.Id == bl.Id)
                    {
                        u.RegisterUsername = bl.RegisterUsername;
                        u.RegisterEmail = bl.RegisterEmail;
                        u.RegisterPassword = bl.RegisterPassword;
                        try
                        {
                            string connectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Users;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
                            SqlConnection con = new SqlConnection(connectionString);
                            con.Open();
                            string query = $"Update users set Uname='{u.RegisterUsername}', Email='{u.RegisterEmail}',Password='{u.RegisterPassword}' where id={u.Id} ";
                            SqlCommand cmd = new SqlCommand(query, con);
                            int effectedRow = cmd.ExecuteNonQuery();
                            if (effectedRow >= 1)
                            {
                                // Clean the previous List and Get Latest Data From DB into it
                                UsersRepos.users.Clear();
                                UsersRepos.Users();
                                return View("Admin", UsersRepos.users);

                            }
                            else
                            {
                                return View();
                            }
                            // users.Add(u);

                        }
                        catch (Exception ex)
                        {
                            ViewBag.Error = ex.Message;
                            return View("Error");
                        }

                    }
                }

            }

            return View();
        }


        // To Remove any User From DB By Finding Its ID in User List
        public ViewResult Remove(int id)
        {

            // Clean the previous List and Get Latest Data From DB into it
            UsersRepos.users.Clear();
            UsersRepos.Users();
            Users u = UsersRepos.users.Find(b => b.Id == id);

            try
            {
                string connectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Users;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
                SqlConnection con = new SqlConnection(connectionString);
                con.Open();
                string query = $"delete from users where id={u.Id} ";
                SqlCommand cmd = new SqlCommand(query, con);
                int effectedRow = cmd.ExecuteNonQuery();
                if (effectedRow >= 1)
                {
                    // Clean the previous List and Get Latest Data From DB into it
                    UsersRepos.users.Clear();
                    UsersRepos.Users();
                    return View("Admin", UsersRepos.users);

                }
                else
                {
                    return View();
                }
                // users.Add(u);

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("Error");
            }


        }





        //It returns the Front Page of Posts Only for Admin 
        public ViewResult UpdatPosts()
        {
            BlogRepos.Clean();
            BlogRepos.GetPosts();
            return View("UpdatePosts", BlogRepos.blog);
        }


        //TO View Any Post Details
        public ViewResult Detail(int id)
        {


            BlogRepos.Clean();
            BlogRepos.GetPosts();
            Blog b = BlogRepos.blog.Find(b => b.Id == id);

            return View("PostDetail", b);
        }


        //IT return the Update Page For Post
        [HttpGet]
        public ViewResult PostUpdate(int id)
        {


            BlogRepos.Clean();
            BlogRepos.GetPosts();
            Blog b = BlogRepos.blog.Find(b => b.Id == id);

            return View("PostUpdate", b);
        }


        //Stores the Updated Attributes into DB
        [HttpPost]
        public ViewResult PostUpdate(Blog bl)
        {
            BlogRepos.Clean();
            BlogRepos.GetPosts();

BlogApp/Views/Shared/Admin.cshtml
@model List<BlogApp.Models.Users>



<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

<center>

    <h1 style="color:white; background-color:black;"> Admin Panel    </h1>
    <h2 style="color:black"> Users </h2>
</center>

  

<table class="table table-dark table-striped">

    <thead>


        <tr>

            <th>Names</th>
            <th>Emails</th>
            <th>Passwords</th>




        </tr>




    </thead>

    <tbody>

        @foreach (BlogApp.Models.Users c in Model)
        {
        <tr>

            <th>@c.RegisterUsername</th>
            <th>@c.RegisterEmail</th>
            <th>@c.RegisterPassword</th>
            <th><a class="btn btn-primary" asp-controller="User" asp-action="Update" asp-route-id="@c.Id">Update</a></th>
            <th><a class="btn btn-danger" asp-controller="User" asp-action="Remove" asp-route-id="@c.Id">Remove</a></th>


        </tr>

        }



    </tbody>



</table>
<center>
    <a class="btn btn-primary" asp-controller="User" asp-action="UpdatPosts">See Posts</a>
</center>

BlogApp/Views/Shared/CreatePost.cshtml
@using BlogApp.Models
@model Blog
<html>

<head>


    <link href="~/css/site.css" rel="stylesheet" />

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>


<body style=" background-image: url('../../images/back.jpg');">



    <center>
        <div class="text-center border border-dark w-50 p-3">

            <h1 style="color: #0000A0;"> Post Your Thoughts.. </h1>


            <form method="post"  asp-controller="User"  asp-action="CreatePost">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="container-fluid w-50 ">
                    <label class="col-form-label" style="color:whitesmoke" asp-for="Title"></label><br>
                    <input class="form-control" asp-for="Title"><br>
                    <span asp-validation-for="Title"></span>

                </div>

                <div class="container-fluid w-75">
                    <label class="col-form-label" style="color:whitesmoke" asp-for="Context"></label><br>
                    <textarea class="form-control h-50 " asp-for="Context"></textarea><br>
                    <span asp-validation-for="Context"></span>

                </div>

                <button class="btn btn-primary" type="submit">Post</button>
            </form>

        </div>


    </center>


</body>








</html>

BlogApp/Views/Shared/Detail.cshtml
@model BlogApp.Models.Blog

<div>

    @{
        Layout = "~/Views/Shared/navbar.cshtml";

    }
</div>
<html>

<head>

    
</head>

<body style=" background-image: url('../../images/front.jpg');">
    <center>
        <div class="card w-50 mt-3" style="width: 18rem; background-color:#696969;">
            <img class="img-thumbnail img-responsive img-circle" style=" max-width: 130px; max-height: 130px; min-height: 130px; min-width: 130px;">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <p class="card-text">@Model.Context</p>
                @if (@Model.refrence==1)
                {
                    <a class="btn btn-dark" asp-controller="Blog" asp-action="Update" asp-route-id="@Model.Id">Update</a>
                    <a class="btn btn-danger" asp-controller="Blog" asp-action="Remove" asp-route-id="@Model.Id">Remove</a>

                }
                
            </div>

        </div>
    </center>


</body>

</html>

BlogApp/Views/Shared/Front.cshtml
<div>

    @{
        Layout = "~/Views/Shared/Posts.cshtml";

    }
</div>

BlogApp/Views/Shared/PostDetail.cshtml
@model BlogApp.Models.Blog

<html>

<head>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

</head>

<body style=" background-image: url('../../images/front.jpg');">
    <center>
        <div class="card w-50 mt-3" style="width: 18rem; background-color:#696969;">
            <img class="img-thumbnail img-responsive img-circle" style=" max-width: 130px; max-height: 130px; min-height: 130px; min-width: 130px;">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <p class="card-text">@Model.Context</p>
                
                    <a class="btn btn-dark" asp-controller="User" asp-action="PostUpdate" asp-route-id="@Model.Id">Update</a>
                    <a class="btn btn-danger" asp-controller="User" asp-action="PostRemove" asp-route-id="@Model.Id">Remove</a>
                
            </div>

        </div>
    </center>


</body>

</html>

BlogApp/Views/Shared/PostUpdate.cshtml
@using BlogApp.Models
@model Blog

<html>

<head>


    <link href="~/css/site.css" rel="stylesheet" />

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>


<body style=" background-image: url('../../images/back.jpg');">



    <center>
        <div class="text-center border border-dark w-50 p-3">

            <h1 style="color: #0000A0;"> Update Post.. </h1>


            <form method="post" asp-controller="User" asp-action="PostUpdate">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="container-fluid w-50 ">
                    <label class="col-form-label" style="color:whitesmoke" asp-for="Title"></label><br>
                    <input class="form-control" asp-for="Title"><br>
                    <span asp-validation-for="Title"></span>

                </div>

                <div class="container-fluid w-75">
                    <label class="col-form-label" style="color:whitesmoke" asp-for="Context"></label><br>
                    <textarea class="form-control h-50 " asp-for="Context"></textarea><br>
                    <span asp-validation-for="Context"></span>

                </div>

                <button class="btn btn-primary" type="submit">Update</button>
            </form>

        </div>


    </center>


</body>








</html>

BlogApp/Views/Shared/Posts.cshtml
<div>
    @RenderBody()
</div>

@model List<BlogApp.Models.Blog>
<div>

    @{
        Layout = "~/Views/Shared/navbar.cshtml";

    }
</div>
<html>

<head>


</head>

<body style=" background-image: url('../../images/front.jpg');">


    <div class="text-center">
        <a class="btn btn-primary pd-1021" asp-controller="Blog" asp-action="Post">Add Post</a>



    </div>
    <center>
        @foreach (BlogApp.Models.Blog b in Model)
        {

            <div class="card w-50 mt-3" style="width: 18rem; background-color:#e2dede; ">
                <img class="img-thumbnail img-responsive img-circle" style=" max-width: 70px; max-height: 70px; min-height: 130px; min-width: 130px;">
                <div class="card-body">
                    <h5 class="card-title">@b.Title</h5>
                    <p class="card-text">@b.Context</p>
                    <a class="btn btn-primary" asp-controller="Blog" asp-action="Detail" asp-route-id="@b.Id">Detail</a>
                </div>
            </div>




        }
    </center>
</body>

</html>

BlogApp/Views/Shared/UpdatePosts.cshtml
@model List<BlogApp.Models.Blog>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <div class="text-center">


        <h1 style="color:white; background-color:black;"> Admin Panel    </h1>
        <h2 style="color:black"> All Posts </h2>

        <a class="btn btn-primary pd-1021" asp-controller="User" asp-action="CreatePost">Create Post</a>
    </div>


<table class="table table-dark table-striped">

    <thead>


        <tr>

            <th>Title</th>
            <th>Context</th>
            <th></th>




        </tr>




    </thead>

    <tbody>

        @foreach (BlogApp.Models.Blog b in Model)
        {
            <tr>

                <td>@b.Title</td>
                <td>@b.Context</td>
                <td>

                    <a class="btn btn-info" asp-controller="User" asp-action="Detail" asp-route-id="@b.Id">Detail</a>
                    


                </td>



            </tr>

        }



    </tbody>


</table>
<center>
    <a class="btn btn-primary" asp-controller="User" asp-action="Login">Logout</a>
</center>

BlogApp/Views/Shared/UpdateUser.cshtml
@model BlogApp.Models.Users


<html>

<head>
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>


<body style=" background-image: url('../../images/back.jpg');">
    <center>
        <div class="text-center border border-dark w-50 p-3">
            <h1 style="color: #0000A0;"> Update </h1>


            <form method="post"  asp-controller="User" asp-action="Update">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="container-fluid w-50">
                    <label class="col-form-label" style="color:whitesmoke" asp-for="RegisterUsername"></label><br>
                    <input class="form-control" asp-for="RegisterUsername"><br>
                    <span asp-validation-for="RegisterUsername"></span>
                </div>

                <div class="container-fluid w-50">
                    <label class="col-form-label" style="color:whitesmoke" asp-for="RegisterEmail"></label><br>
                    <input class="form-control" asp-for="RegisterEmail"><br>
                    <span asp-validation-for="RegisterEmail"></span>
                </div>

                <div class="container-fluid w-50">
                    <label class="col-form-label" style="color:whitesmoke" asp-for="RegisterPassword"></label><br>
                    <input class="form-control" asp-for="RegisterPassword"><br>
                    <span asp-validation-for="RegisterPassword"></span>
                </div>

                <div class="container-fluid w-50">
                    <label class="col-form-label" style="color:whitesmoke" asp-for="ConfirmPassword"></label><br>
                    <input class="form-control" asp-for="ConfirmPassword"><br>
                    <span asp-validation-for="ConfirmPassword"></span>
                </div>

                <div class="container-fluid w-50">
                    <label class="col-form-label" style="color:whitesmoke" asp-for="ProfileImage"></label><br>
                    <input class="form-control" asp-for="ProfileImage"><br>
                    <span asp-validation-for="ProfileImage"></span>

                </div>

                <button class="btn btn-primary" type="submit">Update!</button>
            </form>




        </div>
    </center>


</body>







</html>

BlogApp/Views/Shared/_Layout.cshtml
<div>

    @RenderBody()
</div>

BlogApp/Views/Shared/navbar.cshtml
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />




<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <a class="navbar-brand" href="#">Blog Application</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Front", "User")">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="@Url.Action("About", "User")">About</a>
            </li>

            <li class="nav-item">
                <a class="nav-link active" href="@Url.Action("Login", "User")">Logout</a>
            </li>

            </li>
        </ul>

    </div>
</nav>

<div>
    @RenderBody()
</div>